name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  publish:
    uses: stoe/policies/.github/workflows/policy-node-publish.yml@main
    with:
      npm: false
      gh: true
