name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  publish:
    uses: stoe/policies/.github/workflows/policy-node-publish.yml@main
    with:
      npm: false
      gh: true

  generate-build-provenance:
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - uses: github-early-access/generate-build-provenance@main
        with:
          subject-path: '${{ github.workspace }}/action.yml'
